
name: Auto pull new commits
on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:
  push:
    branches: [14.0]
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: '14.0'
      - name: Fetch from odoo/odoo
        run: |
          git remote add -f upstream "https://github.com/${{ inputs.upstream }}.git" --allow-unrelated-histories
          git remote -v
          git branch --all
          git config --list
          git checkout ${{ inputs.branch }}
          git merge --ff-only upstream/${{ inputs.upstream-branch }}
          git push 
        shell: bash
          
