name: Auto pull new commits
on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: '14.0'
      - name: Config name and email for push action
        run: |
          git config --global user.name 'Hoang Manh'
          git config --global user.email 'manhhoang.vp95@gmail.com'
          git config pull.rebase true
      - name: Fetch from odoo/odoo
        run: |
          git remote add upstream https://github.com/odoo/odoo.git
          git fetch upstream
          git merge upstream/14.0
          git push --force
        shell: bash
