
name: Auto pull new commits
on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:
  push:
    branches: [14.0]
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: '14.0'
      - name: Fetch from odoo/odoo
        run: |
          git config pull.rebase false
          git pull https://github.com/odoo/odoo 14.0 --allow-unrelated-histories
          git commit -m "Fetch and merge upstream odoo"
          git push
          echo "Success"
