
name: Auto pull new commits
on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: '14.0'
      - name: Fetch from odoo/odoo
        run: |
          git pull https://github.com/odoo/odoo 14.0
          git commit -m "Fetch and merge upstream odoo"
          git push
          echo "Success"
