
name: Auto pull new commits
on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: '14.0'
      - name: Fetch from odoo/odoo
        run: |
          git remote add -f upstream "https://github.com/odoo/odoo.git"
          git remote -v
          git branch --all
          git config --list
          git checkout 14.0
          git merge -s ours --no-commit upstream/odoo --allow-unrelated-histories
          git push 
        shell: bash
          
