name: Build Sopen ERP Deb Package

on:
  push:
    branches: [ 14.0 ]
  pull_request:
    branches: [ 14.0 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: view ACCESS_TOKEN\
        run: |
          echo ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/checkout@v2
        with:
          repository: 'SOpen-vn/sopen-odoo-addons'
          ref: '14'
          token: ${{ secrets.ACCESS_TOKEN }}
          path: 'sopen-addons'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            pexpect
      - run: python /home/runner/work/odoo/odoo/setup/package.py --build-deb
