name: Build Sopen ERP Docker Image

on:
  push:
    branches: [ 14.0 ]
  pull_request:
    branches: [ 14.0 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: view ACCESS_TOKEN\
        run: |
          echo ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/checkout@v2
        with:
          repository: 'SOpen-vn/sopen-odoo-addons'
          ref: '14.0'
          token: ${{ secrets.ACCESS_TOKEN }}
